### ISSUE TITLE
[Bug] Handlers cannot be marked as 'Internal', and consumed by another Assembly

### ISSUE THREAD

**Issue by jeffward01** [martinothamar/Mediator#17]
Hello!

# **Scenario**
* I am building a CLI app that cleans the `.nuspec` file (I add some custom settings in my `.nuspec` files, this is unrelated).  
* I am building a nuget package which utilizes [Mediator](https://github.com/martinothamar/Mediator)
* This nuget package will be consumed by other applications of mine.
* The other applications will call `_doSomethingCool.ExecuteSomeCode(someObjectGoesHere);` which will call a method inside my library. The method inside the consumed library will call `_mediator.Send(command);` (I just wanted to explain how the flow works).
* I do not want the internal handlers, or `ISomeCoolService` or `SomeCoolCommand` exposed to applications which consume this library, so I mark all my handlers and services as `internal class` or `internal record` (for the commands and responses)

# Bug
When my application consumes the library which references [Mediator](https://github.com/martinothamar/Mediator), I receive errors, see below:
![image](https://user-images.githubusercontent.com/12589359/157131987-c3bdb366-5f86-438c-a74d-5e3acfa6aec5.png)

Closer view of the errors:
![image](https://user-images.githubusercontent.com/12589359/157132246-51198743-5a0f-44a6-8f50-6adf65d74faa.png)

This leads me to believe that the generated code in the [Mediator](https://github.com/martinothamar/Mediator) library cannot be set to `internal`.

@martinothamar - is this a bug, or just a fact of life with source-generators?

Again - BIG thank you for the library!! I can live with it just fine if the code must be marked as `public`, I am thankful for your beautiful code!

**Comment by martinothamar** [comment]
Hi!

I think I understand why it happens, you have the source generator package installed in the AppConsole project and then have internal handlers defined in a different project right? So the generated code for invoking handlers is referring directly to the handler classes (inside `AddMediator` there is code that is doing `AddSingleton<ICommandHandler<...>, ConcreteHandler>` for example, so we need access to `ConcreteHandler`), which is what is causing this issue. 

I think there are two ways to deal with this:
* Use public
* Ues [InternalsVisibleToAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.internalsvisibletoattribute?view=net-6.0)

I cant think of anything that we can do in the source generator to improve this at the moment, since the generated code needs to be able to reference the type where the source generator package is installed. So we have the same limitations here as in any C# code, its just a bit hidden due to being generated code. Maybe I should have some more diagnostics/warnings for this. Thanks for bringing it up.

**Comment by jeffward01** [comment]
This helps alot! Sorry for the long response back! Thank you!

It is on my 'to-do' list to build a Roslyn Analyzer for this **GREAT LIBURARY** that will check if handlers are marked as 'internal' and other things (that you suggest). As of now it will only check if the handlers are internal, I don't have needs yet for other features. But i would love to add some more features!

Thanks again!
