### ISSUE TITLE
DI registration extensions not working in .Net7

### ISSUE THREAD

**Issue by jmSfernandes** [martinothamar/Mediator#64]
The dependency injection registration, of the Mediator in the Services collection is not working in .NET 7.
![image](https://user-images.githubusercontent.com/45356734/205496323-5342ab8c-7ce9-4743-aebb-496e475b885b.png)

It seems that the extensions can not be found. 

Everything works fine for the same project in .NET6. 
Just changing the SDK makes it work. 

However, I have other dependencies/functionalities from .NET 7 that I require in a specific project. 
And I would like to use Mediator there as well.

I tried with the release candidate (2.0.27-rc, 2.0.28-rc) and with the preview versions (2.1.0-preview2, 2.1.0-preview3).
None seems to work. 
I also tried to do the configuration with:
```csharp
using Mediator;
[assembly: MediatorOptions(Namespace = "SimpleConsole.Mediator", DefaultServiceLifetime = ServiceLifetime.Transient)]
```

But with the same result.

Process to replicate: 

- Create a new API project with .NET 7.
- Import both Mediator.SourceGenerator and Mediator.Abstractions packages from NuGet.
- try to call the `AddMediator()` extension in the `builder.Services` in Program.cs

**Comment by eskaufel** [comment]
I am using it in several .Net7 projects with no issues. In my experience this behaviour is the result of some dependent project or error in the code.

I did test with a new project and it worked just fine 
![image](https://user-images.githubusercontent.com/1670466/205503062-ef75f739-34ce-4cc6-b9da-f95c0c201f94.png)

Do you have the <PrivateAssets> and <IncludeAssets> elements?

**Comment by martinothamar** [comment]
This sounds kind of similar to the issue here: https://github.com/martinothamar/Mediator/issues/58#issuecomment-1320493289
The project built fine and could run etc, but Rider (my version of it at the time) was complaining about `AddMediator` just like in your screenshot. So the red highlighting was only reproduced for me when running the latest version of Rider as of the comment above, and running target framework `net7.0`, but it was just syntax highlighting, it was actually running fine

Is this the case for you as well or does it error out on build?

Same as @eskaufel shows above, I had no issues with the same code in Visual Studio

**Comment by jmSfernandes** [comment]
@martinothamar In my case it wouldn't let me build... (at least from the IDE, didn't try to run it from the CLI)
But the image from @eskaufel made me curious about trying it in Visual Studio.

And you are both absolutely right... 
It Works fine in both Visual Studio 17.4.2 (newest version) 
And also works in Rider 2022.3.9 EAP (Early Access)
![image](https://user-images.githubusercontent.com/45356734/205509629-31c15b47-27af-4b3d-b027-7f2131ec69fb.png)

So I guess its just an error from Rider 2022.2 not fully supporting .NET 7 yet. 

I will close it.
Thank you both for the replies.
