### ISSUE TITLE
Source generator do not process assemblies that does not have direct references to Mediator assembly or types 

### ISSUE THREAD

**Issue by anadale** [martinothamar/Mediator#75]
Hello,

First of all, thank you very much for your excellent product, it is a real pleasure to use it! However, I've stepped over the strange bug (or feature) that is related to the multi-project setup:

Let's imagine that we have three projects:

`MySolution.Abstractions` project references `Mediator.Abstractions` package and contains a class `ApplicationHandlerBase` that serves as a base class for the request handlers of the solution. It also contains a class `ApplicationController`, that provides a method `TResponse ProcessMessage<TRequest, TResponse>(TRequest request)` that retrieves an `IMediator` service from the service provider exposed by `HttpContext` and dispatches a call to `IMediator.Send` using provided request.

`MySolution.Handlers` project references `MySolution.Abstractions` project and implements a handler (`SomeHandler`), derived from `ApplicationHandlerBase` and a controller, derived from `ApplicationController`.

`MySolution.WebApp` is ASP.NET Core application, that references `MySolution.Handlers` project and `Mediator.SourceGenerator` package. The call to `AddMediator` is also in this project.

Now, to the interesting part: with this setup source generator does not generate code for handlers from `MySolution.Handlers`. If I, however, will (redundantly) mark `SomeHandler` as implementing `IRequestHandler` (because it is implementing this interface through the base class) OR directly reference any type from `Mediator.Abstractions` in that project, then handler will be properly registered. It seems that source generator's analyzer skips the project, since the compiler(?) does not add a reference to the assembly `Mediator.Abstractions`. My wild guess is that the problem is [here](https://github.com/martinothamar/Mediator/blob/fdfac6a4f38197be9cc46d65c508ac242b113b59/src/Mediator.SourceGenerator.Implementation/Analysis/CompilationAnalyzer.cs#L314). It looks like analyzer should inspect not only direct, but all references of the compilation. I can come up with a PR if you'll confirm my guess and removing such constraint will not interfere with your vision of the analyzer.

**Comment by martinothamar** [comment]
Hi, thanks for this excellent bug report! Your wild guess is probably spot on, I also suspect that section of the code. It doesn't look like this code accounts for transitive references, so what it looks like you've found out is that Roslyn only includes references in the datastructure if an assembly member is directly referenced. So yes I guess we have to go recursive here to account for this?

I'll gladly accept the PR, and I think it would be a good idea to have a sample application following the structure you describe. It's very useful to keep track of different architecture styles that are being used, so that we can test and verify that they work over time as the project evolves.

**Comment by anadale** [comment]
I think we can close this one, since the PR is merged, thank you!
